apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.19
#     pullSecretRef:
#       name: museum-creds
#       namespace: default
    namespace: wordpress
#    wait: true
    values:
      service:
        type: ClusterIP
    set:
      - name: param1
        value: value2
#   valuesFrom:
#     - configMapKeyRef:
#         key: values.yaml
#         name: default-vals
#         namespace: wordpress
#         optional: false
#     - secretKeyRef:
#         key: svalues.yaml
#         name: svals
#         namespace: wordpress
#         optional: false
  connectionDetails:
    - apiVersion: v1
      kind: Secret
      name: wordpress-example-mariadb
      namespace: wordpress
    - apiVersion: v1
      kind: Service
      name: wordpress-example
      namespace: wordpress
      fieldPath: spec.clusterIP
      toConnectionSecretKey: clusterip
  writeConnectionSecretToRef:
    name: testt
    namespace: crossplane-system
  providerConfigRef:
    name: helm-provider
